apiVersion: v2
appVersion: "1.0"
description: A Helm chart for spring-boot-template App
name: ccpay-refunds-api
home: https://github.com/hmcts/ccpay-refunds-app
version: 0.2.8
maintainers:
  - name: HMCTS Fees and Pay team
dependencies:
  - name: java
    version: 4.0.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
