java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/ccpay/refunds-api:latest'
  ingressHost: ccpay-refunds-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ccpay
  environment:
    POSTGRES_PORT: 5432
    POSTGRES_HOST: ccpay-refunds-api-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_NAME: refunds
    POSTGRES_USERNAME: refunds@ccpay-refunds-api-postgres-db-v11-{{ .Values.global.environment }}
    POSTGRES_CONNECTION_OPTIONS: ?sslmode=require
    SPRING_LIQUIBASE_ENABLED: false
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    ISSUER_URI: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o"
    OIDC_CLIENT_ID: "paybubble"
    OIDC_ISSUER: "https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts"
    OIDC_S2S_MICROSERVICE_NAME: refunds_api
    OIDC_AUDIENCE_LIST: paybubble,cmc_citizen,ccd_gateway
    S2S_AUTHORISED_SERVICES: payment_app,ccpay_bubble,api_gw,ccd_gw,xui_webapp
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    LAUNCH_DARKLY_USER_NAME_PREFIX: '{{ .Values.global.environment }}'
    LIBERATA_OAUTH2_AUTHORIZE_URL: "https://bpacustomerportal.liberata.com/pba/public/oauth/authorize"
    LIBERATA_OAUTH2_TOKEN_URL: "https://bpacustomerportal.liberata.com/pba/public/oauth/token"
    LIBERATA_BASE_URL: "https://lascustomerportaluat.liberata.com"
    REFUND_STATUS_UPDATE_PATH: "/refunds-api/refunds"
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - name: refunds-api-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: refunds-s2s-secret
          alias: OIDC_S2S_SECRET
        - name: paybubble-idam-client-secret
          alias: OIDC_CLIENT_SECRET
        - name: launch-darkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: liberata-api-key
          alias: LIBERATA_API_KEY
        - name: liberata-keys-oauth2-client-id
          alias: LIBERATA_OAUTH2_CLIENT_ID
        - name: liberata-keys-oauth2-client-secret
          alias: LIBERATA_OAUTH2_CLIENT_SECRET
        - name: liberata-keys-oauth2-username
          alias: LIBERATA_OAUTH2_USERNAME
        - name: liberata-keys-oauth2-password
          alias: LIBERATA_OAUTH2_PASSWORD

