java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=allow"
    LOGBACK_REQUIRE_ALERT_LEVEL: 'false'
    LOGBACK_REQUIRE_ERROR_CODE: 'false'
    SPRING_LIQUIBASE_ENABLED: true
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/hmcts
    LAUNCH_DARKLY_USER_NAME_PREFIX: aat
    PAYMENT_API_URL: "http://payment-api-pr-972.service.core-compute-preview.internal"
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: refunds-s2s-secret
          alias: OIDC_S2S_SECRET
        - name: paybubble-idam-client-secret
          alias: OIDC_CLIENT_SECRET
        - name: launch-darkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: liberata-keys-oauth2-client-id
          alias: liberata.oauth2.client.id
        - name: liberata-keys-oauth2-client-secret
          alias: liberata.oauth2.client.secret
        - name: liberata-keys-oauth2-username
          alias: liberata.oauth2.username
        - name: liberata-keys-oauth2-password
          alias: liberata.oauth2.password
        - name: liberata-api-key
          alias: LIBERATA_API_KEY
  postgresql:
    enabled: true
