server:
  port: 9084
spring:
  application:
    name: refunds-api

  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/refunds
    username: refunds
    password: refunds
    properties:
      charSet: UTF-8
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/changelog/db.changelog-master.xml

  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:23443/o
        # Dummy OIDC client required even we are not going to use
        registration:
          oidc:
            client-id: internal
            client-secret: internal
oidc:
  audience-list: internal,paybubble,refunds,payments
  issuer: ${OIDC_ISSUER:http://fr-am:8080/openam/oauth2/hmcts}

auth:
  provider:
    service:
      client:
        baseUrl: http://localhost:23443
  idam:
    client:
      baseUrl: http://localhost:23443
azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}
idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  s2s-authorised:
    services: payment_app,ccpay_bubble,api_gw,ccd_gw,xui_webapp,paybubble
  s2s-auth:
    url: http://localhost:8489
    totp_secret: BBBBBBBBBBBBBBBB
    microservice: paybubble

#Launch Darkly Config
launch:
  darkly:
    sdk:
      key: ${LAUNCH_DARKLY_SDK_KEY:dummy}
    user:
      name: ${LAUNCH_DARKLY_USER_NAME_PREFIX:dummy}@feesandpay.com

launchDarkly:
  connectionTimeout: 3
  socketTimeout: 3
  flushInterval: 10

payments:
  api:
    url: ${PAYMENT_API_URL:http://localhost:9095}

reconciliation-provider:
  api:
    url: ${LIBERATA_BASE_URL:https://lascustomerportaluat.liberata.com}
  refund-status-update-path: ${REFUND_STATUS_UPDATE_PATH:/refunds-api/refunds}
liberata:
  oauth2:
    client:
      id: ${LIBERATA_OAUTH2_CLIENT_ID:id}
      secret: ${LIBERATA_OAUTH2_CLIENT_SECRET:abc}
    username: ${LIBERATA_OAUTH2_USERNAME:username}
    password: ${LIBERATA_OAUTH2_PASSWORD:password}
    authorize:
      url: ${LIBERATA_OAUTH2_AUTHORIZE_URL:https://bpacustomerportal.liberata.com/pba/public/oauth/authorize}
    token:
      url: ${LIBERATA_OAUTH2_TOKEN_URL:https://bpacustomerportal.liberata.com/pba/public/oauth/token}
  api:
    key: ${LIBERATA_API_KEY:abc}


refunds:
  serviceAccount:
    clientId: ${REFUND_SERVICE_ACCOUNT_CLIENT_ID:paybubble}
    clientSecret: ${REFUND_SERVICE_ACCOUNT_CLIENT_SECRET:NVYEC2X7XFSRENTU}
    grantType:  ${REFUND_SERVICE_ACCOUNT_GRANT_TYPE:password}
    username: ${REFUND_SERVICE_ACCOUNT_USERNAME:pragnesh.patel2@hmcts.net}
    password: ${REFUND_SERVICE_ACCOUNT_PASSWORD:LevelAt12}
    scope: ${REFUND_SERVICE_ACCOUNT_SCOPE:openid profile roles search-user}
    redirectUri: ${REFUND_SERVICE_ACCOUNT_REDIRECT_URI:http://localhost:3000/receiver}

notification:
  url: ${NOTIFICATION_API_URL:http://localhost:8185}
  letter-path: ${NOTIFICATION_LETTER_PATH:/letterNotification}
  email-path: ${NOTIFICATION_EMAIL_PATH:/emailNotification}
  email-to-reply: ${EMAIL_TO_REPLY:}
  service-mailbox: ${SERVICE_MAIL_BOX:}
  service-url: ${SERVICE_URL:http://service}

logging:
  level:
    org:
      springframework:
        web: DEBUG

refund:
  search:
    days: 7
