spring:
  application:
    name: bulk-scanning
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/refunds
    username: refunds
    password: refunds
    properties:
      charSet: UTF-8
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/changelog/db.changelog-master.xml

trusted:
  s2s:
    service:
      names: ccpay_bubble,cmc,bulk_scan_payment_processor,api_gw,probate_frontend,divorce_frontend
auth:
  provider:
    service:
      client:
        baseUrl: http://localhost:23443
  idam:
    client:
      baseUrl: http://localhost:23443
