apiVersion: v2
appVersion: "1.0"
description: A Helm chart for spring-boot-template App
name: refunds-app
home: https://github.com/hmcts/ccpay-refunds-app
version: 0.0.1
maintainers:
  - name: HMCTS Fees and Pay team
dependencies:
  - name: java
    version: 3.4.4
    repository: '@hmctspublic'
